[book]
title = "Lux Documentation"
authors = ["Project Lighthouse"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/projectlighthouse/lux"
edit-url-template = "https://github.com/projectlighthouse/lux/edit/master/docs/{path}"
